import OpenAI from "openai";



export async function getTriviaQuestion(apiKey: string): Promise<{
  question: string;
  answer: number;
  options: string[];
  success: boolean;
  hint: string;
}> {
  try {
    const openai = new OpenAI({
      apiKey
    });
    const response = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content:
            `You are a trivia question generator. Provide a multiple-choice trivia question about baseball in JSON format. Ensure the format is: {question: string, options: string[], answerIndex: number, hint: string}. The answerIndex should indicate the correct answer's position in the options array.
            Follow the below criteria for generating the question:
              1. The question should be about baseball.
              2. The question could be related to a player, team, historical event, MLB, baseball rules, baseball pitch, stadiums that could keep the fans engaged and entertained. 
              3. The question can vary from easy to hard.
              4. The question should be something which is not easy to guess while still keeping it interesting.
              5. The question is to entertain the user so keep it fun and engaging. You can use emojis wherever required but do not overkill the question with emojis.
              6. Make sure that hints are not detiled that makes it obvious for the user to guess the answer. It should also be kept fun and engaging for the end user.
              7. Make sure the questions are unique and not repeated.
              8. In the final output, the response should not contain anything except the string which when parsed by the JSON parser of JS should give the object with the above keys. Any other text explaining or any other keywords added in the answer would cause the error. 
              9. Do not append the strings in the options array with any sort of serial numbers or alphabets.
              10. The questions could be like one word MCQs or could be a sentence based MCQs.

            While generating output, takes gaps and pauses to think and analyze the final output generated by you. 
            `,
        },
      ],
      // Sets randomized temp (0-2)
      temperature: Number((Math.random() * 2).toFixed(1)),
    });

    const content = response.choices[0]?.message?.content;

    if (!content) {
      throw new Error("No response from OpenAI API.");
    }

    const parsedData = JSON.parse(content);

    // Validate response format
    if (
      !parsedData.question ||
      !Array.isArray(parsedData.options) ||
      typeof parsedData.answerIndex !== "number" ||
      parsedData.answerIndex < 0 ||
      parsedData.answerIndex >= parsedData.options.length
    ) {
      throw new Error("Invalid response format from OpenAI.");
    }

    return {
      question: parsedData.question,
      options: parsedData.options,
      answer: parsedData.answerIndex,
      hint: parsedData.hint,
      success: true,
    };
  } catch (error) {
    console.error("Error fetching trivia question:", error);
    return {
      question: "",
      options: [],
      answer: -1,
      success: false,
      hint: "",
    };
  }
}
